# Generated by Django 2.2 on 2019-04-05 05:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('market_sector', models.CharField(blank=True, max_length=100)),
                ('security_type_1', models.CharField(blank=True, max_length=100)),
                ('security_type_2', models.CharField(blank=True, max_length=100)),
                ('exchange_code', models.CharField(blank=True, max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cusip', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^[0-9A-Z]{9}$', 'Expecting 9 alphanumeric digits')])),
            ],
        ),
    ]
