# Generated by Django 2.2 on 2019-04-07 05:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cusip_lookup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuniBond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('ticker', models.CharField(blank=True, max_length=100)),
                ('market_sector', models.CharField(blank=True, max_length=100)),
                ('exchange_code', models.CharField(blank=True, max_length=100)),
                ('security_type_1', models.CharField(blank=True, max_length=100)),
                ('security_type_2', models.CharField(blank=True, max_length=100)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cusip', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^[0-9A-Z]{9}$', 'invalid CUSIP')])),
            ],
        ),
        migrations.DeleteModel(
            name='Security',
        ),
    ]
